# Generated by Django 3.1 on 2023-11-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20231109_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
